name: Run JMeter Performance Test

on:  
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  jmeter-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # Ensure repo is checked out

      - name: Install JMeter
        run: |
          sudo apt update
          wget https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.5.tgz
          tar -xvzf apache-jmeter-5.5.tgz
          sudo mv apache-jmeter-5.5 /opt/jmeter
          echo "export PATH=\$PATH:/opt/jmeter/bin" >> ~/.bashrc
          source ~/.bashrc

      - name: Run JMeter Tests
        run: |
          ls -l data/  # Check if CSV file is available
          jmeter -n -t tests/Syma-Creators.jmx -l data/5000.csv -Jjmeter.save.saveservice.output_format=csv --addprop /dev/null

      - name: Upload JMeter Results
        uses: actions/upload-artifact@v4
        with:
          name: jmeter-results
          path: results.jtl

      - name: Upload JMeter Report
        uses: actions/upload-artifact@v4
        with:
          name: jmeter-report
          path: report/
