name: Run JMeter Performance Test

on:
  workflow_dispatch:  
  # push:
    # branches:
      # - main
  # pull_request:
    # branches:
      # - main

jobs:
  jmeter-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  

      - name: Install JMeter (Manual)
        run: |
          sudo apt update
          wget https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.5.tgz
          tar -xvzf apache-jmeter-5.5.tgz
          sudo mv apache-jmeter-5.5 /opt/jmeter
          echo "export PATH=\$PATH:/opt/jmeter/bin" >> ~/.bashrc
          source ~/.bashrc

      - name: Configure JMeter Security Settings
        run: |
          echo "xstream.whitelist=org.apache.jmeter.save.ScriptWrapper" | sudo tee -a /opt/jmeter/bin/jmeter.properties

      - name: Run JMeter Tests
        run: |
          export JVM_ARGS="-Xms2g -Xmx8g"
          /opt/jmeter/bin/jmeter -n -t tests/topposa.jmx -l data/csvOutput.csv -Jjmeter.save.saveservice.output_format=csv --addprop /dev/null

      - name: Debug JMeter Output
        run: |
          ls -l data/
          cat data/csvOutput.csv || echo "CSV file is empty!"

      - name: Upload JMeter CSV Results
        uses: actions/upload-artifact@v4
        with:
          name: jmeter-results
          path: data/csvOutput.csv
