name: Run JMeter Performance Test

on:  
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  jmeter-test:
    runs-on: ubuntu-latest  # Use a Linux runner
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # Get repo code

      - name: Install JMeter
        run: |
          sudo apt update
          sudo apt install -y jmeter

      - name: Run JMeter Tests
        run: |
          jmeter -n -t tests/Syma-Creators.jmx -l results.jtl -e -o report/

      - name: Upload JMeter Results
        uses: actions/upload-artifact@v3
        with:
          name: jmeter-results
          path: results.jtl

      - name: Upload JMeter Report
        uses: actions/upload-artifact@v3
        with:
          name: jmeter-report
          path: report/
